spring.application.name=operator-kvd

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kvd_stat}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.fail-on-empty-beans=false

server.port=${SERVER_PORT:8080}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

dadata.api.token=${DADATA_TOKEN:}

app.backup.pg-dump-path=${PG_DUMP_PATH:pg_dump}
app.admin.initial-password=${ADMIN_INITIAL_PASSWORD:ChangeMe123}
