insert into genders (name, code) values ('Мужской', 'MALE') on conflict do nothing;
insert into genders (name, code) values ('Женский', 'FEMALE') on conflict do nothing;
insert into citizen_types (name, code) values ('Город', 'URBAN') on conflict do nothing;
insert into citizen_types (name, code) values ('Село', 'RURAL') on conflict do nothing;
insert into state_groups (name, code) values ('Красноярск', 'KRASNOYARSK') on conflict do nothing;
insert into state_groups (name, code) values ('Край', 'REGION') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Сифилис', 'SYPHILIS') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Гонорея', 'GONORRHEA') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Чесотка', 'SCABIES') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Трихомониаз', 'TRICHOMONIASIS') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Хламидиоз', 'CHLAMYDIA') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Герпес', 'HERPES') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Остроконечные кондиломы', 'CONDYLOMAS') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Микозы', 'MYCOSES') on conflict do nothing;
insert into diagnosis_groups (name, code) values ('Микроспория', 'MICROSPORIA') on conflict do nothing;
insert into social_groups (name, code) values ('Работающий', 'WORKING') on conflict do nothing;
insert into social_groups (name, code) values ('Неработающий', 'UNEMPLOYED') on conflict do nothing;
insert into social_groups (name, code) values ('Пенсионер', 'PENSIONER') on conflict do nothing;
insert into social_groups (name, code) values ('Студент', 'STUDENT') on conflict do nothing;
insert into social_groups (name, code) values ('Учащийся Школа', 'SCHOOL') on conflict do nothing;
insert into social_groups (name, code) values ('Дошкольник Организован', 'KINDERGARTEN_ORG') on conflict do nothing;
insert into social_groups (name, code) values ('Дошкольник Неорганизован', 'KINDERGARTEN_UNORG') on conflict do nothing;